### ISSUE TITLE
[TR]Build Error

### ISSUE THREAD

**Issue by ghost** [yasirtug/ni-translate#11]
`qmake ni-translate.pro -spec linux-g++` dümdüz böyle girince oluyor, `qmake ni-translate.pro -spec linux-g++ -config ocr` yaptığımda make dedikten sonra `include/mainwindow.h:67:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<QuickEditor> mQuickEditor;
          ^~~~~~~~~~
Makefile:450: recipe for target 'main.o' failed
make: *** [main.o] Error 1
` bu hatayı alıyorum. O paket yüklü bu arada ocr'siz versiyonu çalışıyor.

**Comment by yasirtug** [comment]
mainwindow.h'a `#include <memory>` ekleyip bir daha deneyebilir misin

**Comment by ghost** [comment]
olmadı hocam

**Comment by yasirtug** [comment]
derleyici farklılığıyla bir ilgisi var herhalde. build-essential paketini yükleyip dener misin bir de

`sudo apt install build-essential`

**Comment by ghost** [comment]
O paket yükü

**Comment by yasirtug** [comment]
bilemedim o zaman :D memory include'unu kesin doğru yaptın mı? c++ biliyor musun bilmiyorum, dosyanın tepesine diğer include'ların yanına koyacaktın... kayıt ettiğinden de emin ol... prize taktın mı kontrol et... kusura bakma başka kurşunum kalmadı :D

**Comment by ghost** [comment]
C++ Bilmiyorum da include'u diğer includeların altına yaptım neyse bekleyelim elbet bi yolu bulunur :D

**Comment by yasirtug** [comment]
olması lazım ya, olmazsa da sanırım hatanın değişmesi lazım. mainwindow.cpp değil mainwindow.h'a eklemen gerek. zaten oradaysa kb...

**Comment by yasirtug** [comment]
veya yeni değişiklikleri çek, olması gerektiğini sandığım halini push'ladım

**Comment by ghost** [comment]
```
src/mainwindow.cpp: In member function ‘void MainWindow::grabScreen()’:
src/mainwindow.cpp:174:34: error: ‘class QWidget’ has no member named ‘screen’; did you mean ‘scroll’?
     QScreen *screen =  window()->screen();
                                  ^~~~~~
                                  scroll
Makefile:456: recipe for target 'mainwindow.o' failed
```
Bu sefer bunu verdi.

**Comment by yasirtug** [comment]
o kullandığım metot en yeni versiyonlarda varmış, şimdi değiştirip yeni versiyonu push'ladım. eğer başka bi yerden yine patlarsa qt sürümünü güncellemen gerekiyor olabilir:
`sudo apt install qt5-default`

**Comment by ghost** [comment]
Çalıştı, emeğine sağlık :D

**Comment by yasirtug** [comment]
sen de sağ ol, iyi test etmiş olduk :D

**Comment by ghost** [comment]
@yasirtug Şimdi manga okurken OCR'yi deneyeceğim, bakalım sıkıntı çıkarsa yine issue açarım :D
