### ISSUE TITLE
[TR] Problems about OCR

### ISSUE THREAD

**Issue by ghost** [yasirtug/ni-translate#13]
Bazen, segmentation fault diyor sadece bazen de Bus error, ne hata kodu ne başka bir şey var.

**Comment by ghost** [comment]
Segmentation Fault, font'u algılayamama sorunuymuş sanırım ama diğerini bilmiyorum

**Comment by yasirtug** [comment]
bende de birkaç kere çökmüştü ama uğraşıp tekrarlayamayınca yok saymıştım, yine uğraştım yine tekrarlayamadım. ilgisi olabileceğini düşündüğüm birkaç yeri düzenledim ama düzelmiş olma ihtimali çok düşük. özellikle nasıl tekrarlandığını bilemeyince bakacak pek bir yer olmuyor :D font'u algılayamama derken ocr sırasında mı? öyle bir sebepten patlamaması gerek

**Comment by ghost** [comment]
>>font'u algılayamama derken ocr sırasında mı?

Okuduğum yerde öyle yazıyordu emin değilim, yeni hali ile deneyeyim bir de.

**Comment by yasirtug** [comment]
diğer issue için biraz daha bekleteceğim bu arada. bu halinin de bi seçenek olarak kalmasını istiyorum, nasıl bir şey yapacağımı tam düşünmedim henüz

**Comment by ghost** [comment]
```
src/translator.cpp: In member function ‘void Translator::translate(QString, QString, QString)’:
src/translator.cpp:70:57: error: ‘errorOccurred’ is not a member of ‘QNetworkReply’
     errorSigConnection = connect(reply, &QNetworkReply::errorOccurred, this, &Translator::getError);

```
böyle bir hata aldım, netten baktım da sonuç bulamadım :D O değilde bende cıkan hataların neden coğu nette yok :D

**Comment by yasirtug** [comment]
:D gene en yeni sürümü kullandığım için.
[burada error](https://doc.qt.io/qt-5.12/qnetworkreply.html)
[burada errorOccurred](https://doc.qt.io/qt-5/qnetworkreply.html)
o errorOccurred'i error'a çevirirsen düzelecek muhtemelen, kodu şimdi herkeste çalışacak şekilde düzenleyip atıcam

**Comment by yasirtug** [comment]
> ```
> src/translator.cpp: In member function ‘void Translator::translate(QString, QString, QString)’:
> src/translator.cpp:70:57: error: ‘errorOccurred’ is not a member of ‘QNetworkReply’
>      errorSigConnection = connect(reply, &QNetworkReply::errorOccurred, this, &Translator::getError);
> ```
> 
> O değilde bende cıkan hataların neden coğu nette yok :D

değişiklik çok yeni olduğu için henüz yeterince karşılaşılmamış :D

**Comment by yasirtug** [comment]
> o errorOccurred'i error'a çevirirsen düzelecek muhtemelen, kodu şimdi herkeste çalışacak şekilde düzenleyip atıcam

düzelmiyormuş asdjqwdsa qt 5.9.9 yükleyip denedim şimdi, bu sefer gerçekten düzelttim, atıyorum :D

**Comment by ghost** [comment]
Hala aynı unlucky :D
```
Warning: Invalid resolution 0 dpi. Using 70 instead.
Segmentation fault
```

**Comment by yasirtug** [comment]
ne kadar sık oluyor?  
üstteki uyarıyı da düzelttim şimdi, basitmiş ama ilk aradığımda sonuç bulamamıştım

**Comment by ghost** [comment]
Hiç çalısmıyor bende segmentation fault vermese bile bus error veriyor, mangalarda bir de yazılar siyah arka plan beyaz, aslında daha rahat okuması lazım ama bilemedim

**Comment by yasirtug** [comment]
manga hangi dil? bir de dili değiştirince bir şey değişiyor mu

**Comment by yasirtug** [comment]
sen şimdiye kadar ocr'ı hiç kullanamadın mı yani

**Comment by ghost** [comment]
İngilizce, bir kere denk geldi wikipedia'da ondan sonra hiç çalısmadı.

**Comment by yasirtug** [comment]
geç cevap için kb, sen bu yorumu attığında uyumuştum, gece aşağıdakini yazarken dikkatimi başka bir şey çekmiş sonrası karanlık :D

> 
> şimdi yaptığım bir hatayı fark ettim, ben ilk denemeler yaparken `tesseract-ocr` paketi aracılığıyla eng dil paketini de kurmuşum. fakat dil paketi sadece `libtesseract-dev` paketini indirince gelmiyor. dolayısıyla varsayılan olarak eng ile başlamaya çalıştığından tesseract hata veriyor.
> ```
> Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
> Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
> Failed loading language 'eng'
> Tesseract couldn't load any languages!
> Could not initialize tesseract.
> ```
> sen şu hatayı alıp sonra kendin kurdun sanırım dil paketini?

asıl merak ettiğim, tesseract sürümünün güncel olup olmadığıydı çünkü internette eski sürümden kaynaklı ocr sırasında crash bildirilerine denk geldim. hangi distro, distro'nun hangi sürümü ve bulabilirsen paketlerin hangi sürümleri, bunları atabilir misin

**Comment by ghost** [comment]
Xubuntu 18.04, qt5-default (5.9.5+dfsg-0ubuntu2.5 and others),libtesseract-dev (4.00), tesseract 5.0.0-alpha-781-gb19e3, libxi-dev (2:1.7.9-1)

**Comment by yasirtug** [comment]
discord gelebilir misin? :D ıptısçıktıs#2976
tesseract alpha ile ilgili olabilir diyeceğim ama ordan bişi çıkmayabilir, baksam iyi olacak

**Comment by yasirtug** [comment]
closed for good: 97a558e45e84580a498846ad2ebc36e1a7bb1294
