### ISSUE TITLE
Incorrect result. May be access is forbidden due to too many requests

### ISSUE THREAD

**Issue by VolkovIlia** [yasirtug/ni-translate#16]
![image](https://user-images.githubusercontent.com/43730119/106019335-95a64580-60d3-11eb-9ec1-aa327310068b.png)

Always get error. Installed from aur.

**Comment by yasirtug** [comment]
I don't maintain this repo anymore. Any particular reason you should use ni-translate? There is [crow-translate](https://github.com/crow-translate/crow-translate) if there isn't.
