### ISSUE TITLE
Noob friendly installation guide needed

### ISSUE THREAD

**Issue by runo280** [yasirtug/ni-translate#2]
I was dreaming to build an QTranslate alternative for Linux, found your app, thanks.
After installing dependency, excuted these commands one by one in `ni-translate` folder:

    qmake ni-translate.pro -spec linux-g++
    make

Now I have these files:
![screenshot_2019-02-18_18-20-57](https://user-images.githubusercontent.com/13608702/52958961-71e80a00-33aa-11e9-9a69-1999970312e9.png)
What should I do for run the app?
I'm on Xubuntu 18.10.

I thinks it will be more usefull if you provide more detailed guide for installing and running the app.

**Comment by yasirtug** [comment]
Hello, now run `sudo ./ni-translate` from that folder. Please write if it will work. Thanks for the feedback btw, i will try to improve the guide.

**Comment by runo280** [comment]
:sweat_smile: After creating this issue found how to run it, I went back here and saw you responded to it, so quick :rocket: 
Yes it works well, I set `Scroll Lock` button for hire it.
It will be awesome if you add some features when you have free time.
- Translate current text on changing language
- A place to input text directly in main window + translate button
- Tray icon for launching app by click

**Comment by yasirtug** [comment]
It is awesome that some other guy around the globe is using my program, this may be a first :D You have increased my motivation on improving the program. Now i will add some to-do's, including your advices. Thanks.
