### ISSUE TITLE
A error when make

### ISSUE THREAD

**Issue by jacjochay** [yasirtug/ni-translate#7]
Hello, I got an error while building the project. How to fix it? Thanks.
I'm using Deepin OS.

~/Downloads/translate$ make
/usr/lib/x86_64-linux-gnu/qt5/bin/uic ntranslate/mainwindow.ui -o ui_mainwindow.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic ntranslate/settingswindow.ui -o ui_settingswindow.h
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -Intranslate -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o ntranslate/main.cpp
make: g++: Command not found
Makefile:378: recipe for target 'main.o' failed
make: *** [main.o] Error 127

**Comment by yasirtug** [comment]
Hi, you should have executable `g++` (GNU C++ Compiler) in your PATH and you can get it by installing package `g++`.
After that, if you still have build problems, try installing `build-essential` package.
Hope you will find this helpful.

**Comment by jacjochay** [comment]
Thank you!
