### ISSUE TITLE
Build project problem

### ISSUE THREAD

**Issue by benio-star** [yasirtug/ni-translate#8]
Hi.
After running `make` I received:

> /usr/bin/ld: cannot open output file ni-translate: Is a directory
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:164: ni-translate] Error 1
> 

![image](https://user-images.githubusercontent.com/25732294/75344684-6a9bec00-589b-11ea-8437-a7f14ad57095.png)

**Comment by yasirtug** [comment]
Hi, 
Reason of this error is that you run make in the root of ni-translate directory. If you just want to use the program, you can simply run every command in the source directory. It should produce no error.
