### ISSUE TITLE
[TR] OCR Implementation

### ISSUE THREAD

**Issue by ghost** [yasirtug/ni-translate#9]
Selamlar hocam, buna bir tesseract entegre etsen var ya o kadar iyi olur ki, film vs. izleyenler için de baya kolaylık olur. 
Saygılarımla.

**Comment by yasirtug** [comment]
Yaptım :D interSubs sayesinde senin ihtiyacın kalmamış sanırım ama iyi oldu bence. Oynatıcıda altyazıya siyah arkaplan yapılırsa çalışır. Onun dışında da iyi fikirmiş, seçilemeyen her türlü text'te kullanmak üzere refleks oluştu bile bende. Denemek istersen readme'ye yazdım talimatları, fikir için sağ ol :D
